"""
Django settings for bytegirls project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ========== SEGURIDAD ==========
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure---=vx!!l2$6t0uc-@dzqk-3=3l%30aa#$!+1g%7jyq8tl2s*yt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir todas las conexiones (para túnel SSH - SOLO DESARROLLO)
ALLOWED_HOSTS = ['*']


# ========== APLICACIONES ==========
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "oficios",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bytegirls.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bytegirls.wsgi.application"


# ========== BASE DE DATOS ==========
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ========== VALIDACIÓN DE CONTRASEÑAS ==========
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ========== INTERNACIONALIZACIÓN ==========
LANGUAGE_CODE = "es-es"
TIME_ZONE = "America/La_Paz"
USE_I18N = True
USE_TZ = True


# ========== ARCHIVOS ESTÁTICOS ==========
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# ========== ARCHIVOS MEDIA (IMÁGENES) ==========
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ========== CONFIGURACIÓN DE EMAIL (Gmail) ==========
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mishelldiaz400@gmail.com"
EMAIL_HOST_PASSWORD = "ogfj wvfd bifb hyym"
DEFAULT_FROM_EMAIL = "CHAMBA <mishelldiaz400@gmail.com>"


# ========== CONFIGURACIÓN DE SESIÓN ==========
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"


# ========== CONFIGURACIÓN DE SEGURIDAD (para túnel SSH) ==========
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Tamaño máximo de subida de archivos (10MB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# ========== CONFIGURACIÓN DE CSRF (para túnel) ==========
# Permite cualquier origen para el túnel
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8080',
    'http://localhost:8080',
    'http://0.0.0.0:8080',
    'https://782274df250dbb06-138-199-50-140.serveousercontent.com',
    'https://*.serveousercontent.com',
    'http://*.serveousercontent.com',
    'https://*.serveo.net',
    'http://*.serveo.net',
]


# ========== CONFIGURACIÓN DE CACHE ==========
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# ========== CONFIGURACIÓN DE LOGGING ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"