# Generated by Django 4.2.13 on 2026-05-25 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('revisada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta laboral'), ('servicio', 'Servicio ofrecido'), ('estado', 'Estado personal')], default='estado', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('oficio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('precio', models.CharField(blank=True, max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('trabajador', models.ForeignKey(limit_choices_to={'perfil__tipo': 'trabajador'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario'), ('publicacion', 'Publicación'), ('usuario', 'Usuario')], max_length=20)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficios.comentario')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficios.publicacion')),
                ('reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortafolioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
                ('trabajador', models.ForeignKey(limit_choices_to={'perfil__tipo': 'trabajador'}, on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trabajador', 'Trabajador de Oficio'), ('empleador', 'Empleador')], max_length=15)),
                ('telefono', models.CharField(max_length=25)),
                ('ubicacion', models.CharField(max_length=150)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('oficios', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_personal', models.TextField(blank=True, null=True)),
                ('anios_experiencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fotos_portafolio', models.TextField(blank=True, null=True)),
                ('contactos_externos', models.JSONField(blank=True, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('rubro', models.CharField(blank=True, max_length=100, null=True)),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_calificaciones', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('oficio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('remuneracion', models.CharField(blank=True, max_length=100)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('empleador', models.ForeignKey(limit_choices_to={'perfil__tipo': 'empleador'}, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('elemento_afectado', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='oficios.publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='oficios.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '⭐ Muy malo'), (2, '⭐⭐ Malo'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_hechas', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='oficios.oferta')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='oficios.servicio')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('calificador', 'calificado', 'oferta', 'servicio')},
            },
        ),
    ]
