# Generated by Django 6.0.5 on 2026-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0012_historialadmin_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
