# Generated by Django 6.0.5 on 2026-05-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0013_comentario_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
