# Generated by Django 6.0.5 on 2026-05-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0014_publicacion_revisada'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
